"""Standalone documentation maintenance agent core."""

from .baseline import (
    BASELINE_SCHEMA_VERSION,
    BaselineError,
    baseline_from_report,
    ensure_matches,
    load_baseline,
    validate_baseline,
    write_baseline,
)
from .delta import build_delta
from .events import EVENTS_SCHEMA_VERSION, DocEventStore, EventStoreError
from .evolution import (
    APPROVAL_SCHEMA_VERSION,
    EVOLUTION_SCHEMA_VERSION,
    EVOLUTION_STATES,
    ApprovalRequired,
    EvolutionError,
    create_evolution,
    load_approval,
    load_evolution,
    transition_evolution,
    validate_approval,
    validate_evolution,
    write_evolution,
)
from .gate import (
    GATE_SCHEMA_VERSION,
    VERIFY_SCHEMA_VERSION,
    GateError,
    GateMismatch,
    build_gate_record,
    load_gate,
    load_report,
    report_fingerprint,
    validate_gate,
    validate_report,
    verify_gate,
    write_gate,
)
from .profile import (
    DEFAULT_PROFILE_NAME,
    PROFILE_SCHEMA_VERSION,
    ProfileConfigError,
    load_profile,
    validate_profile,
)
from .rules import (
    DEFAULT_RULES_PATH,
    RULES_SCHEMA_VERSION,
    RulesConfigError,
    load_rules,
    rules_fingerprint,
    validate_rules,
)
from .scanner import ScanError, scan_repository

__all__ = [
    "DEFAULT_RULES_PATH",
    "EVENTS_SCHEMA_VERSION",
    "GATE_SCHEMA_VERSION",
    "VERIFY_SCHEMA_VERSION",
    "APPROVAL_SCHEMA_VERSION",
    "BASELINE_SCHEMA_VERSION",
    "BaselineError",
    "DEFAULT_PROFILE_NAME",
    "EVOLUTION_SCHEMA_VERSION",
    "EVOLUTION_STATES",
    "ApprovalRequired",
    "EvolutionError",
    "GateError",
    "GateMismatch",
    "DocEventStore",
    "EventStoreError",
    "PROFILE_SCHEMA_VERSION",
    "ProfileConfigError",
    "RULES_SCHEMA_VERSION",
    "RulesConfigError",
    "ScanError",
    "load_rules",
    "load_profile",
    "load_baseline",
    "load_approval",
    "load_evolution",
    "load_gate",
    "load_report",
    "rules_fingerprint",
    "report_fingerprint",
    "baseline_from_report",
    "build_delta",
    "build_gate_record",
    "create_evolution",
    "ensure_matches",
    "validate_baseline",
    "write_baseline",
    "scan_repository",
    "transition_evolution",
    "validate_approval",
    "validate_evolution",
    "validate_gate",
    "validate_report",
    "validate_rules",
    "validate_profile",
    "write_evolution",
    "verify_gate",
    "write_gate",
]
